// code_blocks/getting-started/rc-billing/displaying-products.tsx
const PaywallPage: React.FC<{
  purchases: Purchases;
  appUserId: string;
}> = ({ purchases, appUserId }) => {
  const [offerings, setOfferings] = useState<Offerings | null>(null);
  const [customerInfo, setCustomerInfo] = useState<CustomerInfo | null>(null);

  useEffect(() => {
    purchases
      .getOfferings(appUserId)
      .then((offerings) => setOfferings(offerings));
    purchases
      .getCustomerInfo(appUserId)
      .then((customerInfo) => setCustomerInfo(customerInfo));
  }, [purchases, appUserId]);

  if (
    !customerInfo ||
    !offerings ||
    !offerings.current ||
    Object.keys(offerings.current.packages).length === 0
  ) {
    return null;
  }

  if (Object.keys(customerInfo.entitlements.active).length > 0) {
    return <h2>You are subscribed!</h2>;
  }

  return (
    <>
      <h2>Available packages</h2>
      <ul>
        {Object.entries(offerings.current.packages).map(
          ([key, pkg]) =>
            pkg.rcBillingProduct !== null && (
              <li key={key}>
                {key}: {(pkg.rcBillingProduct.currentPrice?.amount ?? 0) / 100}
                {pkg.rcBillingProduct.currentPrice?.currency} /{" "}
                {pkg.rcBillingProduct.normalPeriodDuration}
                <button
                  onClick={() => {
                    purchases
                      .purchasePackage(appUserId, pkg)
                      .then(({ customerInfo }) =>
                        setCustomerInfo(customerInfo)
                      );
                  }}
                >
                  Buy
                </button>
              </li>
            )
        )}
      </ul>
    </>
  );
};

// code_blocks/getting-started/rc-billing/displaying-products.svelte
<script lang="ts">
  import type {
    Purchases,
    CustomerInfo,
    Offerings,
  } from "@revenuecat/purchases-js";
  import { onMount } from "svelte";

  export let purchases: Purchases;
  export let userId: string;

  let offerings: Offerings | undefined;
  let customerInfo: CustomerInfo | undefined;
  onMount(async () => {
    offerings = await purchases?.getOfferings(userId);
    customerInfo = await purchases?.getCustomerInfo(userId);
  });
</script>

{#key customerInfo}
  {#if customerInfo && offerings}
    {#if Object.keys(customerInfo.entitlements.active).length > 0}
      <p>You are subscribed to the following entitlements:</p>
      <ul>
        {#each Object.entries(customerInfo.entitlements.active) as [key, value]}
          <li>{key}: {value.expirationDate}</li>
        {/each}
      </ul>
    {:else}
      <p>You are not subscribed!</p>
      <ul>
        {#each Object.entries(offerings.current?.packages ?? {}) as [key, pkg]}
          <li>
            {key}:
            {(pkg.rcBillingProduct.currentPrice?.amount ?? 0) / 100}
            {pkg.rcBillingProduct.currentPrice?.currency}
            / {pkg.rcBillingProduct.normalPeriodDuration}
            <button
              on:click={async () => {
                customerInfo = (await purchases.purchasePackage(userId, pkg))
                  .customerInfo;
              }}
            >
              Buy!
            </button>
          </li>
        {/each}
      </ul>
    {/if}
  {/if}
{/key}
